create table if not exists T_USERS (
	ID INT PRIMARY KEY,
	USERNAME VARCHAR(40) UNIQUE NOT NULL,
	EMAIL VARCHAR(40) UNIQUE NOT NULL,
	PASSWORD CHAR(32) NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	UPDATE_TIME TIMESTAMP NOT NULL
)